version: "3.9"

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
      - "7473:7473"
    volumes:
      - "./data/neo4j:/data"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4j_ACCEPT_LICENSE_AGREEMENT: "yes"
