AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - com.crackbyte::aws-lambda-demo
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
#  AwsHelloLambdaFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      Handler: com.crackbyte.LambdaHandler::handleRequest
#      Runtime: java17
#      CodeUri: .
#      MemorySize: 512
#      Policies: AWSLambdaBasicExecutionRole
#      Timeout: 30
#      Events:
#        ProxyResource:
#          Type: Api
#          Properties:
#            Path: /hello/{proxy+}
#            Method: any
#  AwsDemoLambdaHandlerFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      Handler: com.crackbyte.DemoLambdaHandler::handleRequest
#      Runtime: java17
#      CodeUri: .
#      MemorySize: 512
#      Policies: AWSLambdaBasicExecutionRole
#      Timeout: 30
#      Events:
#        ProxyResource:
#          Type: Api
#          Properties:
#            Path: /demo/{proxy+}
#            Method: any
  AwsStreamLambdaHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.crackbyte.StreamLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  AwsLambdaDemoPingApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/test'
    Export:
      Name: AwsLambdaDemoPingApi
  AwsLambdaDemoHelloApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/demo/test'
    Export:
      Name: AwsLambdaDemoHelloApi
